---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: fluentd-service-account
  namespace: pas-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-namespace-read
  namespace: pas-system
rules:
- apiGroups: ["*"]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-service-account-pod-namespace-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-namespace-read
subjects:
- kind: ServiceAccount
  name: fluentd-service-account
  namespace: pas-system



