apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: log-cache
    git:
      url: https://github.com/cloudfoundry/log-cache-release
      ref: v2.8.0
  - path: cf-k8s-logging-fluent
    git:
      url: https://github.com/cloudfoundry/cf-k8s-logging-fluent
      ref: 550374b941fee74157dcd8f82125edd84f04c96f
