apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: log-cache
    git:
      url: https://github.com/cloudfoundry/log-cache-release
      ref: 60d4baaf8de8a31c213306adfce44e3f4ea98e29
  - path: cf-k8s-logging-fluent
    git:
      url: https://github.com/cloudfoundry/cf-k8s-logging-fluent
      ref: 7e943d3c0273c2f807812409caa9d3b705f7da8c
