---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-forwarder
  namespace: cf-system
  labels:
    app: fluentd-forwarder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd-forwarder
  template:
    metadata:
      labels:
        app: fluentd-forwarder
    spec:
      serviceAccountName: fluentd-service-account
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      imagePullSecrets:
      - name: image-registry-credentials
      containers:
      - name: fluentd
        image: #TODO Fill in the desired Log Cache Image
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc
        - name: varlog
          mountPath: /var/log
        - name: varvcapstore
          mountPath: /var/vcap/store
        - name: dockercontainers
          mountPath: /var/lib/docker/containers
        - mountPath: /ca
          name: ca
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: fluentd-config
        configMap:
          name: fluent-forwarder-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varvcapstore
        hostPath:
          path: /var/vcap/store
      - name: dockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: ca
        secret:
          secretName: log-cache-ca
