resources:
- name: fluentd-syslog
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/fluent-plugin-syslog_rfc5424
    private_key: ((cf-loggregator-oauth-bot-key))
    ignore_paths:
    - lib/fluent-plugin-syslog_rfc5424/version.rb

- name: fluentd-syslog-push
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/fluent-plugin-syslog_rfc5424
    private_key: ((cf-loggregator-oauth-bot-key))

jobs:
  - name: test-ruby-plugin
    plan:
      - get: fluentd-syslog
        trigger: true
      - task: run-tests
        config:
          image_resource:
            type: registry-image
            source: { repository: ruby, tag: 2.7 }
          platform: linux
          inputs:
          - name: fluentd-syslog
          run:
            path: /bin/bash
            args:
              - -c
              - |
                cd fluentd-syslog
                bundle install
                bundle exec rake test
  - name: bump-gem-version
    plan:
    - get: fluentd-syslog
      trigger: true
      passed: ["test-ruby-plugin"]
    - task: gem bump version
      config:
        image_resource:
          type: registry-image
          source: { repository: ruby, tag: 2.7 }
        platform: linux
        inputs:
        - name: fluentd-syslog
        outputs:
        - name: fluentd-syslog-commited
          path: fluentd-syslog
        run:
          path: /bin/bash
          args:
          - -c
          - |
            git config --global user.email "cf-loggregator@pivotal.io"
            git config --global user.name "Log Egress CI"

            cd fluentd-syslog
            gem install gem-release
            gem bump -v rc
    - put: fluentd-syslog-push
      params:
        repository: fluentd-syslog-commited

  - name: release-gem
    plan:
    - get: fluentd-syslog-push
      trigger: true
      passed: ["bump-gem-version"]

    - task: release-gem
      config:
        image_resource:
          type: registry-image
          source: { repository: ruby, tag: 2.7 }
        platform: linux
        inputs:
        - name: fluentd-syslog-push
        params:
          API_KEY: ((gem-api-key))
        run:
          path: /bin/bash
          args:
          - -c
          - |
            cd fluentd-syslog-push
            mkdir ~/.gem
            echo $API_KEY > ~/.gem/credentials
            chmod 0600 ~/.gem/credentials
            bundle install
            gem build fluent-plugin-syslog_rfc5424
            gem push *.gem

