resources:
- name: fluentd-syslog
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/fluent-plugin-syslog_rfc5424
    private_key: ((cf-loggregator-oauth-bot-key))
    ignore_paths:
    - lib/fluent-plugin-syslog_rfc5424/version.rb

- name: log-cache-release
  type: git
  source:
    branch: develop
    uri: git@github.com:cloudfoundry/log-cache-release
    private_key: ((cf-loggregator-oauth-bot-key))

- name: fluentd-syslog-push
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/fluent-plugin-syslog_rfc5424
    private_key: ((cf-loggregator-oauth-bot-key))

- name: syslog-server-docker
  type: docker-image
  source:
    username: ((logcache-docker.username))
    password: ((logcache-docker.password))
    repository: logcache/syslog-server
- name: log-cache-docker
  type: docker-image
  source:
    username: ((logcache-docker.username))
    password: ((logcache-docker.password))
    repository: logcache/log-cache
- name: log-cache-gateway-docker
  type: docker-image
  source:
    username: ((logcache-docker.username))
    password: ((logcache-docker.password))
    repository: logcache/log-cache-gateway
- name: cf-auth-proxy-docker
  type: docker-image
  source:
    username: ((logcache-docker.username))
    password: ((logcache-docker.password))
    repository: logcache/log-cache-cf-auth-proxy

jobs:
  - name: test-ruby-plugin
    plan:
      - get: fluentd-syslog
        trigger: true
      - task: run-tests
        config:
          image_resource:
            type: registry-image
            source: { repository: ruby, tag: 2.7 }
          platform: linux
          inputs:
          - name: fluentd-syslog
          run:
            path: /bin/bash
            args:
              - -c
              - |
                cd fluentd-syslog
                bundle install
                bundle exec rake test
  - name: bump-gem-version
    plan:
    - get: fluentd-syslog
      trigger: true
      passed: ["test-ruby-plugin"]
    - task: gem bump version
      config:
        image_resource:
          type: registry-image
          source: { repository: ruby, tag: 2.7 }
        platform: linux
        inputs:
        - name: fluentd-syslog
        outputs:
        - name: fluentd-syslog-commited
          path: fluentd-syslog
        run:
          path: /bin/bash
          args:
          - -c
          - |
            git config --global user.email "cf-loggregator@pivotal.io"
            git config --global user.name "Log Egress CI"

            cd fluentd-syslog
            gem install gem-release
            gem bump -v rc
    - put: fluentd-syslog-push
      params:
        repository: fluentd-syslog-commited

  - name: release-gem
    plan:
    - get: fluentd-syslog-push
      trigger: true
      passed: ["bump-gem-version"]

    - task: release-gem
      config:
        image_resource:
          type: registry-image
          source: { repository: ruby, tag: 2.7 }
        platform: linux
        inputs:
        - name: fluentd-syslog-push
        params:
          API_KEY: ((gem-api-key))
        run:
          path: /bin/bash
          args:
          - -c
          - |
            cd fluentd-syslog-push
            mkdir ~/.gem
            echo $API_KEY > ~/.gem/credentials
            chmod 0600 ~/.gem/credentials
            bundle install
            gem build fluent-plugin-syslog_rfc5424
            gem push *.gem

  - name: test-log-cache
    plan:
    - get: log-cache-release
      trigger: true

    - task: test-log-cache
      config:
        image_resource:
          type: registry-image
          source: { repository: golang }
        platform: linux
        inputs:
        - name: log-cache-release
        run:
          path: /bin/bash
          args:
          - -c
          - |
            cd log-cache-release/src
            go test -mod=vendor ./...

  - name: build-images
    plan:
    - get: log-cache-release
      trigger: true
      passed: ["test-log-cache"]
    - in_parallel:
      - put: syslog-server-docker
        params:
          dockerfile: log-cache-release/src/cmd/syslog-server/Dockerfile
          build: log-cache-release/src
      - put: log-cache-docker
        params:
          dockerfile: log-cache-release/src/cmd/log-cache/Dockerfile
          build: log-cache-release/src
      - put: log-cache-gateway-docker
        params:
          dockerfile: log-cache-release/src/cmd/gateway/Dockerfile
          build: log-cache-release/src
      - put: cf-auth-proxy-docker
        params:
          dockerfile: log-cache-release/src/cmd/cf-auth-proxy/Dockerfile
          build: log-cache-release/src




