#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-forwarder-config
  namespace: cf-system
data:
  fluent-bit.conf: |
    # Inputs
    [INPUT]
      Name dummy
      Tag forwarded
      Dummy {"log": "This is a test log from a fluent bit log producer","app_id":"11111111-1111-1111-1111-111111111111","instance_id":"1","source_type": "APP"}

    [OUTPUT]
      Name forward
      Match *
      Host fluentd-forwarder-ingress
